apiVersion: v1
kind: Service
metadata:
  name: {{ include "oom-watcher.fullname" . }}
  labels:
    {{- include "oom-watcher.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "oom-watcher.selectorLabels" . | nindent 4 }}
