version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix
      prefix-development: chore
    groups:
      aya:
        patterns:
          - "aya*"

  - package-ecosystem: docker
    directories:
      - "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: chore

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: ci
