extends: default

rules:
  line-length:
    max: 120
  document-start: disable
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
  braces:
    max-spaces-inside: -1
    max-spaces-inside-empty: -1
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: true
    check-multi-line-strings: false
