apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oom-watcher
  namespace: kube-system
  labels:
    app: oom-watcher
spec:
  selector:
    matchLabels:
      app: oom-watcher
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_node_name]
      targetLabel: kubernetes_node
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: kubernetes_namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: kubernetes_pod_name